repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
  - id: ruff
    args: ["--exclude", "^test/"]
    files: "^cuallee/.*.py"