repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
      - id: ruff
        args: 
          # Exclude .py files in the root folder and test/ folder
          ["--exclude", "^test/"]
        # Include only files under the cuallee folder
        files: "^cuallee/"
        additional_dependencies: []  # Optional additional dependencies if needed