site_name: cuallee
nav:
    - Home: index.md
    - Getting Started:
      - Installation: installation.md
      - Dependencies: dependencies.md
      - Catalogue: catalogue.md
    - Frameworks:
      - Dataframes: frameworks/index.md
      - Pandas: pandas/index.md
      - PySpark: pyspark/index.md
      - DuckDb: duckdb/index.md
      - Polars: polars/index.md
      - Snowpark: snowpark/index.md
      - BigQuery: bigquery/index.md
      - Daft: daft/index.md
    - Code Reference: 
      - Check: module/check.md
      - Rule: module/rule.md
theme:
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  name: material

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    logo: material/marker-check
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - attr_list  
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
extra_css:
  - stylesheets/extra.css